set(THREE_LIB_TP___ROOT ${CMAKE_CURRENT_LIST_DIR})

set(COCOS_LIB_NAME "THREE_LIB_TP__")
add_library(${COCOS_LIB_NAME} STATIC IMPORTED GLOBAL)
set_target_properties(${COCOS_LIB_NAME} PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${THREE_LIB_TP___ROOT}/include"
    IMPORTED_LOCATION "${THREE_LIB_TP___ROOT}/lib/lib${COCOS_LIB_NAME}.a"
)
